/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
static yyconst short int yy_accept[284] =
    {   0,
        0,    0,  102,  100,   99,    1,   84,  100,  100,   90,
       83,  100,   78,   79,   88,   87,   75,   86,   82,   89,
       10,   10,   76,   72,   91,   77,   92,   95,   98,   80,
       81,   93,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   73,
       94,   74,   85,   27,    0,   18,    0,    0,    0,    0,
       32,   74,   28,   37,    0,    0,   30,   20,   33,   21,
       34,   19,   16,    2,    3,   31,   17,   10,    0,   13,
        0,   81,   73,   80,   22,   24,    0,   26,   25,   23,
        0,   98,   38,   98,   98,   98,   98,   98,   98,   47,

       98,   98,   98,   98,   98,   98,   55,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   39,   29,    0,    0,    0,    0,   14,    0,   16,
       11,    0,   17,    0,   15,   12,   35,    0,    0,   36,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   53,   98,   56,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,    0,    0,    0,    0,   16,    0,   16,    0,
       17,   15,   12,    0,   40,   98,   42,   43,   98,   98,
       98,   98,   49,   50,   98,   98,   54,   57,   97,   98,

       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   69,   98,   98,    6,    0,    0,    0,   16,
        5,   41,   44,   98,   98,   98,   98,   52,   98,   98,
       98,   96,   60,   98,   98,   98,   98,   98,   98,   67,
       98,   98,   71,    0,    0,   98,   98,   48,   51,   98,
       59,   61,   62,   63,   64,   65,   98,   98,   98,    0,
        0,   98,   46,   98,   66,   98,   98,    0,    4,   45,
       58,   68,   70,    0,    4,    0,    0,    7,    9,    0,
        9,    8,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   31,
       31,   31,   31,   31,   33,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   31,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   31,   48,   49,   50,   51,
       52,   53,   31,   54,   55,   56,   57,   58,   59,   60,
       61,   62,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[67] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    1,    4,    1,
        5,    1,    1,    1,    1,    1,    1,    6,    1,    7,
        7,    4,    1,    4,    4,    1,    1,    8,    8,    8,
        9,    9,    9,    9,    1,    1,    1,    1,    8,    8,
        8,    8,    8,    8,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[293] =
    {   0,
        0,    0,  742,  743,  743,  743,  716,   66,   91,  109,
      126,  704,  743,  743,  714,  122,  743,  123,  121,  125,
      134,  141,  712,  743,  147,  712,  120,  743,  729,  743,
      743,  710,  136,  146,  150,  158,  157,  169,  151,  153,
      168,  172,  171,  173,  181,  174,  175,  178,  185,  743,
      170,  743,  743,  743,  213,  743,  275,  202,  691,  682,
      743,  743,  743,  743,  176,  196,  743,  743,  743,  743,
      743,  743,  322,  743,  743,  743,  326,  356,  342,  335,
        0,  743,  743,  743,  707,  743,  713,  743,  743,  705,
        0,  722,  743,  337,  206,  341,  212,  343,  179,  338,

      342,  346,  353,  354,  357,  365,  721,  366,  372,  371,
      373,  374,  375,  376,  379,  393,  380,  383,  384,  391,
      395,  743,  743,  681,    0,  682,  684,  743,  395,  743,
      405,  435,  743,  194,  437,  411,  743,  678,  705,  743,
      394,  422,  410,  397,  438,  426,  452,  455,  456,  457,
      463,  715,  459,  714,  464,  465,  466,  467,  468,  469,
      470,  471,  472,  473,  475,  477,  476,  478,  480,  481,
      482,  488,  713,  672,  669,  212,  514,  484,  743,  387,
      518,  743,  508,  691,  709,  483,  708,  707,  489,  496,
      490,  500,  706,  705,  501,  503,  704,  703,  702,  505,

      511,  506,  484,  519,  529,  535,  544,  545,  547,  557,
      546,  549,  701,  561,  562,  743,  656,  649,  550,  560,
      743,  698,  697,  567,  566,  569,  570,  696,  572,  571,
      575,  686,  685,  577,  576,  582,  578,  586,  588,  684,
      589,  591,  683,  634,  634,  593,  595,  668,  664,  594,
      663,  662,  656,  649,  648,  647,  599,  596,  600,  648,
      609,  601,  641,  603,  640,  604,  615,    0,  234,  638,
      617,  243,  241,  224,  623,  593,  219,  615,    0,  609,
        0,  621,  743,  658,  664,  671,  674,  677,  679,  687,
      690,  693

    } ;

static yyconst short int yy_def[293] =
    {   0,
      283,    1,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  284,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  285,  283,  283,  283,  286,  283,
      283,  283,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  283,
      283,  283,  283,  283,    8,  283,  283,   55,  283,  283,
      283,  283,  283,  283,  284,  284,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      287,  283,  283,  283,  283,  283,  288,  283,  283,  283,
       55,  286,  283,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  283,  283,   55,   57,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  287,  283,  283,  288,  283,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,   55,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,

      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  283,  283,  283,  283,  283,
      283,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  286,
      286,  286,  286,  283,  283,  286,  286,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  286,  283,
      283,  286,  286,  286,  286,  286,  286,  289,  283,  286,
      286,  286,  286,  290,  283,  291,  290,  283,  292,  283,
      292,  283,    0,  283,  283,  283,  283,  283,  283,  283,
      283,  283

    } ;

static yyconst short int yy_nxt[810] =
    {   0,
        4,    5,    6,    5,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   29,
       29,   29,   29,   29,   30,    4,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   29,   40,   29,   41,   42,
       29,   29,   43,   44,   45,   46,   47,   48,   49,   29,
       29,   29,   50,   51,   52,   53,   55,   55,   55,   55,
       55,   55,   56,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   57,   57,   57,   57,   57,   57,   57,

       55,   58,   55,   55,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   55,   55,
       55,   55,   59,   61,   62,   63,   68,   60,   74,   70,
       73,   73,   91,   75,   89,   90,   69,   71,   72,   76,
       64,   77,   91,   78,   78,   83,   91,   91,   77,   91,
       78,   78,   79,   91,   91,   80,   80,   81,   84,   79,
       85,   86,   80,   80,   91,   91,   79,   91,   91,   91,
       91,   91,   80,   79,   91,  283,  128,   91,   96,   80,
       80,   91,   94,   81,  122,   97,  107,   80,  283,   95,

       99,   98,  106,  108,  283,  101,   65,  102,   55,  100,
      110,   66,  283,  135,  135,  112,  103,  104,  283,  109,
      105,  113,  146,  276,  111,  119,  114,  115,  276,  120,
      121,  177,  177,  123,  118,  275,  116,   55,  275,  117,
       55,   55,   55,   55,   55,   55,   55,  283,  142,  283,
      144,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   56,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,  124,   55,  125,  125,   55,   55,   55,   55,

       55,   55,  125,  125,  125,  125,  125,  125,  125,   55,
       58,   55,   55,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,   55,   55,   55,
       55,   73,   73,  283,  283,  131,  131,  283,  283,  283,
      129,  130,  283,  130,  132,  133,  134,  133,  134,  283,
      283,  135,  135,  283,  129,  130,   80,   80,  132,  133,
      130,  283,  283,   77,  133,   78,   78,  283,  283,  283,
      283,  283,  283,   80,   79,  283,  283,   80,   80,  283,
      283,   80,  141,  145,  147,  143,  148,  283,   79,  283,

      283,  283,  149,  283,   80,  151,  181,  181,  150,  176,
      152,  176,   80,  160,  177,  177,  283,  156,  158,  157,
      153,  154,  155,  162,  131,  131,  166,  161,  283,  159,
      168,  164,  283,  178,  179,  167,  179,  170,  169,  171,
      163,  172,  183,  183,  283,  185,  165,  178,  179,  180,
      188,  180,  187,  179,  181,  181,  135,  135,  283,  183,
      186,  283,  283,  283,  191,  283,  182,  183,  182,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      182,  283,  283,  283,  283,  182,  283,  283,  283,  283,
      283,  192,  189,  190,  283,  283,  283,  193,  219,  195,

      219,  196,  283,  220,  220,  194,  283,  283,  198,  283,
      197,  283,  283,  201,  206,  199,  200,  283,  210,  203,
      214,  205,  213,  204,  202,  283,  212,  232,  207,  211,
      222,  208,  209,  177,  177,  283,  215,  181,  181,  183,
      183,  283,  224,  130,  223,  130,  225,  133,  226,  133,
      283,  283,  283,  283,  227,  283,  183,  130,  228,  231,
      229,  133,  130,  283,  183,  230,  133,  283,  283,  220,
      220,  234,  283,  283,  233,  283,  283,  283,  283,  220,
      220,  283,  283,  283,  283,  237,  235,  238,  283,  179,
      236,  179,  283,  241,  283,  283,  240,  283,  239,  283,

      283,  283,  283,  179,  243,  283,  283,  283,  179,  283,
      283,  248,  278,  278,  247,  232,  242,  246,  252,  253,
      249,  283,  254,  283,  275,  251,  250,  275,  282,  282,
      257,  256,  280,  255,  278,  278,  264,  259,  266,  258,
      282,  282,  265,  270,  283,  272,  283,  283,  267,  262,
      263,  269,  268,  283,  283,  283,  271,  273,   65,   65,
       65,   65,  283,   65,   65,   65,   65,   87,  283,  283,
      283,   87,   87,   92,  283,  261,  260,   92,   92,   92,
      136,  136,  139,  139,  139,  139,  274,  274,  277,  283,
      283,  283,  283,  277,  277,  277,  279,  279,  279,  281,

      281,  281,  283,  283,  283,  245,  244,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  221,  218,  217,  216,
      283,  283,  138,  184,  175,  174,  173,  283,  283,  140,
      138,  137,  127,  126,   93,   91,   88,   82,   67,   66,
       54,  283,    3,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283
    } ;

static yyconst short int yy_chk[810] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    9,   10,   10,   11,   16,    9,   20,   18,
       19,   19,   33,   20,   27,   27,   16,   18,   18,   20,
       11,   21,   34,   21,   21,   25,   35,   39,   22,   40,
       22,   22,   21,   37,   36,   21,   21,   21,   25,   22,
       25,   25,   22,   22,   41,   38,   21,   43,   42,   44,
       46,   47,   21,   22,   48,   99,   65,   45,   35,   22,
       21,   49,   33,   21,   51,   35,   40,   22,   66,   34,

       36,   35,   39,   40,   58,   37,   66,   37,   58,   36,
       42,   65,   95,  134,  134,   44,   37,   38,   97,   41,
       38,   45,   99,  277,   43,   47,   45,   45,  274,   48,
       49,  176,  176,   51,   46,  269,   45,   58,  269,   45,
       55,   55,   55,   55,   55,   55,   55,  273,   95,  272,
       97,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   73,   73,   94,  100,   77,   77,   96,  101,   98,
       73,   73,  102,   73,   77,   77,   79,   77,   79,  103,
      104,   79,   79,  105,   73,   73,   80,   80,   77,   77,
       73,  106,  108,   78,   77,   78,   78,  110,  109,  111,
      112,  113,  114,   80,   78,  115,  117,   78,   78,  118,
      119,   80,   94,   98,  100,   96,  101,  120,   78,  116,

      141,  121,  102,  144,   78,  104,  180,  180,  103,  129,
      105,  129,   78,  113,  129,  129,  143,  110,  112,  111,
      106,  108,  109,  115,  131,  131,  117,  114,  142,  112,
      119,  116,  146,  131,  131,  118,  131,  120,  119,  120,
      115,  121,  136,  136,  145,  141,  116,  131,  131,  132,
      144,  132,  143,  131,  132,  132,  135,  135,  147,  136,
      142,  148,  149,  150,  146,  153,  135,  136,  135,  151,
      155,  156,  157,  158,  159,  160,  161,  162,  163,  164,
      135,  165,  167,  166,  168,  135,  169,  170,  171,  186,
      203,  147,  145,  145,  172,  189,  191,  148,  178,  150,

      178,  151,  190,  178,  178,  149,  192,  195,  155,  196,
      153,  200,  202,  158,  163,  156,  157,  201,  167,  160,
      171,  162,  170,  161,  159,  204,  169,  203,  164,  168,
      186,  165,  166,  177,  177,  205,  172,  181,  181,  183,
      183,  206,  190,  177,  189,  177,  191,  181,  192,  181,
      207,  208,  211,  209,  195,  212,  183,  177,  196,  202,
      200,  181,  177,  210,  183,  201,  181,  214,  215,  219,
      219,  205,  225,  224,  204,  226,  227,  230,  229,  220,
      220,  231,  235,  234,  237,  208,  206,  209,  236,  220,
      207,  220,  238,  212,  239,  241,  211,  242,  210,  246,

      250,  247,  258,  220,  215,  257,  259,  262,  220,  264,
      266,  226,  276,  276,  225,  229,  214,  224,  234,  235,
      227,  267,  236,  271,  275,  231,  230,  275,  280,  280,
      239,  238,  278,  237,  278,  278,  250,  242,  258,  241,
      282,  282,  257,  262,  270,  266,  265,  263,  259,  246,
      247,  261,  260,  256,  255,  254,  264,  267,  284,  284,
      284,  284,  253,  284,  284,  284,  284,  285,  252,  251,
      249,  285,  285,  286,  248,  245,  244,  286,  286,  286,
      287,  287,  288,  288,  288,  288,  289,  289,  290,  243,
      240,  233,  232,  290,  290,  290,  291,  291,  291,  292,

      292,  292,  228,  223,  222,  218,  217,  213,  199,  198,
      197,  194,  193,  188,  187,  185,  184,  175,  174,  173,
      154,  152,  139,  138,  127,  126,  124,  107,   92,   90,
       87,   85,   60,   59,   32,   29,   26,   23,   15,   12,
        7,    3,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  283,  283,  283,  283,  283,  283,  283,  283,  283,

      283,  283,  283,  283,  283,  283,  283,  283,  283
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c_lexer.l"
#define INITIAL 0
#line 11 "c_lexer.l"
//int yylineno = 1;
char datatype[100] = "dummy";
int tl;
char next;
#include <stdio.h>
#include <string.h> 
#line 646 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 19 "c_lexer.l"

#line 799 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 284 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 743 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "c_lexer.l"
{ yylineno++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "c_lexer.l"
{ multicomment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "c_lexer.l"
{ singlecomment(); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "c_lexer.l"
{ return INCLUDE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "c_lexer.l"
{
    strncpy(yylval.str, yytext, sizeof(yylval.str)-1);
	yylval.str[sizeof(yylval.str)-1] = '\0';
    return HEADER;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 31 "c_lexer.l"
{
    strncpy(yylval.str, yytext, sizeof(yylval.str)-1);
	yylval.str[sizeof(yylval.str)-1] = '\0';
    return HEADER;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 37 "c_lexer.l"
{ return DEFINE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 38 "c_lexer.l"
{ return DEFINE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 39 "c_lexer.l"
{ return DEFINE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "INT"); return CONSTANT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "FLOAT"); return CONSTANT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "c_lexer.l"
{  insertToConstTable(yytext, yylineno, "STRING"); return STRING_LITERAL; } 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "c_lexer.l"
{  return PTR_OP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "c_lexer.l"
{  return INC_OP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "c_lexer.l"
{  return DEC_OP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "c_lexer.l"
{  return LEFT_OP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "c_lexer.l"
{  return RIGHT_OP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "c_lexer.l"
{  return LE_OP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "c_lexer.l"
{  return GE_OP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "c_lexer.l"
{  return EQ_OP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "c_lexer.l"
{  return NE_OP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "c_lexer.l"
{  return AND_OP; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "c_lexer.l"
{  return OR_OP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "c_lexer.l"
{  return MUL_ASSIGN; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "c_lexer.l"
{  return DIV_ASSIGN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "c_lexer.l"
{  return MOD_ASSIGN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "c_lexer.l"
{  return ADD_ASSIGN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "c_lexer.l"
{  return SUB_ASSIGN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "c_lexer.l"
{  return LEFT_ASSIGN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "c_lexer.l"
{  return RIGHT_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "c_lexer.l"
{  return AND_ASSIGN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "c_lexer.l"
{  return XOR_ASSIGN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "c_lexer.l"
{  return OR_ASSIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "c_lexer.l"
{ return AUTO; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "c_lexer.l"
{ return BREAK; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "c_lexer.l"
{ return CASE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 77 "c_lexer.l"
{ return CHAR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 78 "c_lexer.l"
{ return CONST; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "c_lexer.l"
{ return CONTINUE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "c_lexer.l"
{ return DEFAULT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "c_lexer.l"
{ return DO; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 82 "c_lexer.l"
{ return DOUBLE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 83 "c_lexer.l"
{ return ELSE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "c_lexer.l"
{ return ENUM; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "c_lexer.l"
{ return EXTERN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "c_lexer.l"
{ strcpy(datatype, "FLOAT"); tl = yylineno; return FLOAT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "c_lexer.l"
{ return FOR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "c_lexer.l"
{ return GOTO; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "c_lexer.l"
{ return IF; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "c_lexer.l"
{ strcpy(datatype, "INT"); tl = yylineno; return INT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "c_lexer.l"
{ return LONG; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "c_lexer.l"
{ return REGISTER; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "c_lexer.l"
{ return RETURN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "c_lexer.l"
{ return SHORT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "c_lexer.l"
{ return SIGNED; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "c_lexer.l"
{ return SIZEOF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "c_lexer.l"
{ return STATIC; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "c_lexer.l"
{ return STRUCT; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "c_lexer.l"
{ return SWITCH; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "c_lexer.l"
{ return TYPEDEF; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "c_lexer.l"
{ return UNION; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 102 "c_lexer.l"
{ return UNSIGNED; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 103 "c_lexer.l"
{ return VOID; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 104 "c_lexer.l"
{ return VOLATILE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 105 "c_lexer.l"
{ return WHILE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 108 "c_lexer.l"
{  strcpy(datatype, "dummy"); return(';'); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 109 "c_lexer.l"
{  return('{'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 110 "c_lexer.l"
{  return('}'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 111 "c_lexer.l"
{  return(','); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 112 "c_lexer.l"
{  return(':'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 113 "c_lexer.l"
{  return('='); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 114 "c_lexer.l"
{  return('('); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 115 "c_lexer.l"
{  return(')'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 116 "c_lexer.l"
{  return('['); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 117 "c_lexer.l"
{  return(']'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 118 "c_lexer.l"
{  return('.'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 119 "c_lexer.l"
{  return('&'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 120 "c_lexer.l"
{  return('!'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 121 "c_lexer.l"
{  return('~'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 122 "c_lexer.l"
{  return('-'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 123 "c_lexer.l"
{  return('+'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 124 "c_lexer.l"
{  return('*'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 125 "c_lexer.l"
{  return('/'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 126 "c_lexer.l"
{  return('%'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 127 "c_lexer.l"
{  return('<'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 128 "c_lexer.l"
{  return('>'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 129 "c_lexer.l"
{  return('^'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 130 "c_lexer.l"
{  return('|'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 131 "c_lexer.l"
{  return('?'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 132 "c_lexer.l"
{ insertToHash(yytext,"PROCEDURE",yylineno); return IDENTIFIER; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 133 "c_lexer.l"
{ insertToHash(yytext,"PROCEDURE",yylineno); return IDENTIFIER; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 134 "c_lexer.l"
{  
						if(strcmp(datatype, "dummy")==0)
							return IDENTIFIER;
						else 
						{
							insertToHash(yytext,datatype,yylineno);
							return IDENTIFIER; 
						}
					}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 143 "c_lexer.l"
{  }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 144 "c_lexer.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 145 "c_lexer.l"
ECHO;
	YY_BREAK
#line 1403 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 284 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 284 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 283);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 145 "c_lexer.l"


struct cnode
{
	char num[50];
	//int lno;
	char type[20];
};
struct cnode ctable[100];
int ccount = 0;

void insertToConstTable(char *num, int l, char *type)
{
	strcpy(ctable[ccount].num, num);
	strcpy(ctable[ccount].type, type);
	//ctable[ccount].lno = l;
	ccount++;
}

void disp()
{
	int i;
	printf("\n\n------------------------------CONSTANT TABLE------------------------------\n");
	printf("--------------------------------------------------------------------------\n");
	printf("Value \t\t|\tData Type\t\t\n");
	printf("--------------------------------------------------------------------------\n");
	for(i=0;i<ccount;i++)
	{
		printf("%s\t\t\t", ctable[i].num);
		printf("%s\t\t\t\n", ctable[i].type);
		//printf("\t%d\t\n", ctable[i].lno);
	}
	printf("\n\n");
}

struct node
{
	char token[100];
    	char attr[100];
    	//int line[100];
    	int line_count;
	struct node *next;
};

struct hash
{
	struct node *head;
	int hash_count;
};

struct hash hashTable[1000];
int eleCount = 1000;

struct node * createNode(char *token, char *attr, int l)
{
	struct node *newnode;
	newnode = (struct node *) malloc(sizeof(struct node));
	strcpy(newnode->token, token);
	strcpy(newnode->attr, attr);
	//newnode->line[0] = l;
	newnode->line_count = 1; 
	newnode->next = NULL;
	return newnode;
}

int hashIndex(char *token)
{
	int hi=0;
	int l,i;
	for(i=0;token[i]!='\0';i++)
	{
		hi = hi + (int)token[i];
	}
	hi = hi%eleCount;
	return hi;
}

void insertToHash(char *token, char *attr, int l)
{
	int flag=0;
	int hi;
	hi = hashIndex(token);
	struct node *newnode = createNode(token, attr, l);
	/* head of list for the bucket with index "hashIndex" */
	if (hashTable[hi].head==NULL)
	{
		hashTable[hi].head = newnode;
	        hashTable[hi].hash_count = 1;
	        return;
	}
	struct node *myNode;
    	myNode = hashTable[hi].head;
	while (myNode != NULL)
    	{
        	if (strcmp(myNode->token, token)==0)
        	{
            		flag = 1;
            		//myNode->line[(myNode->line_count)++] = l;
            		if(strcmp(myNode->attr, attr)!=0)
            		{
            			strcpy(myNode->attr, attr);
            		}
            		break;
        	}
        	myNode = myNode->next;
    	}
	if(!flag)
	{
		//adding new node to the list
		newnode->next = (hashTable[hi].head);
		//update the head of the list and no of nodes in the current bucket
		hashTable[hi].head = newnode;
		hashTable[hi].hash_count++;
	}
	return;
}

void display()
{
    	struct node *myNode;
    	int i,j, k=1;
    	printf("\n-----------------------------------------Symbol Table---------------------------------------------\n");
    	printf("--------------------------------------------------------------------------------------------------");
    	printf("\nToken \t\t|\tToken Type \t\t\t\t\t \n");
        printf("--------------------------------------------------------------------------------------------------\n");
    	for (i = 0; i < eleCount; i++)
    	{
        	if (hashTable[i].hash_count == 0)
            		continue;
        	myNode = hashTable[i].head;
        	if (!myNode)
            		continue;
        	while (myNode != NULL)
        	{
            		//printf("%d\t\t", k++);
            		printf("%s\t\t\t", myNode->token);
            		printf("%s\t\t\t", myNode->attr);
            		/*for(j=0;j<(myNode->line_count);j++)
            			printf("%d  ",myNode->line[j]);*/
            		printf("\n");
            		myNode = myNode->next;
        	}
	}
	printf("--------------------------------------------------------------------------------------------------\n");
   	return;
}

yywrap()
{
	return(1);
}
multicomment()
{
	char c, c1;
	while ((c = input()) != '*' && c != 0);
	c1=input();
	if(c=='*' && c1=='/')
	{
		c=0;
	}
	if (c != 0)
		putchar(c1);
}
singlecomment()
{
	char c;
	while(c=input()!='\n');
	if(c=='\n')
		c=0;
	if(c!=0)
		putchar(c);
}
